# Generated by Django 5.1.7 on 2025-03-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, null=True)),
                ("telefono", models.CharField(max_length=200, null=True)),
                ("correo", models.CharField(max_length=200, null=True)),
                (
                    "fecha_de_creacion",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, null=True)),
                ("precio", models.FloatField(null=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[("Interior", "Interior"), ("Exterior", "Exterior")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("descripcion", models.CharField(max_length=200, null=True)),
                (
                    "fecha_de_creacion",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Pendiente", "Pendiente"),
                            ("En salida para entrega", "En salida para entrega"),
                            ("Entregado", "Entregado"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "fecha_de_creacion",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "Cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_tienda.cliente",
                    ),
                ),
                (
                    "Producto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_tienda.producto",
                    ),
                ),
            ],
        ),
    ]
